name = "cloudflare-internship-assessment-summer2020"
type = "javascript"
account_id = "0a40c6f39b703dff5745234b60b41ecc"
workers_dev = true

[env.production]
route = "*stewartdulaney.com/cloudflare-internship-assessment-summer2020"
zone_id = "fc775f27d092890417acf6474755a750"
